### PR TITLE
Css

### PR DESCRIPTION
**Pull request by RushikeshJachak**

### CODE REVIEW

**Comment by RushikeshJachak** [comment]
Website now has new style(a bit).

**Comment by RushikeshJachak** [comment]
the site now has a new background.

**Comment by sushant-j** [comment]
Hey @RushikeshJachak - I just checked your changes..  are you sure you submitted the latest changes?
The styles look a bit under-developed. 
Attaching screenshot for reference.

new backgroun

**Comment by sushant-j** [comment]
Also, for suggesting further changes, please update the master branch, so you'll have all the commits made by others as well.

**Comment by RushikeshJachak** [comment]
I dont know why it is showing like that,i have uploaded both the images and had styled for it.
Attaching a schreenshot how it looks along with the files

**Pull request closed without merging**
